
# Manipulación de Arreglos con NumPy  
**Curso:** Programación Numérica  
**Objetivo:** Aprender a crear, modificar y consultar datos en arreglos NumPy.

En esta clase veremos:  
- Creación de arrays  
- Indexación y slicing  
- Mutabilidad y vistas  
- Funciones para generar arrays especiales  
- Copias y referencias  
- Breve ejemplo de graficación con Matplotlib



## 1. Creación de un array y operaciones básicas
En Python, un array de NumPy es similar a un vector o matriz en MATLAB, pero con algunas diferencias clave en la mutabilidad y el manejo de índices.


In [1]:

import numpy as np

# Crear un arreglo de 1D
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

# Imprimir el último elemento
print(a[-1])

# Modificar un elemento (los arrays son mutables)
a[0] = 10
print(a)


[1 2 3 4 5 6]
6
[10  2  3  4  5  6]



## 2. Slicing (cortes) y vistas
Al cortar un array (`slicing`), **no** se crea una copia independiente, sino una *vista* que comparte la misma memoria.  
Esto significa que si modificamos la vista, también cambia el array original.


In [2]:

# Tomamos los primeros 3 elementos (esto es una vista, no una copia)
print(a[:3])

# Creamos una vista desde el índice 3 hasta el final
b = a[3:]

# Modificamos el primer elemento de la vista
b[0] = 40

# El array original también se ve modificado
print(a)


[10  2  3]
[10  2  3 40  5  6]



## 3. Arrays de más de una dimensión
Podemos crear arreglos de 2D (matrices) y acceder a sus elementos usando la notación `[fila, columna]`.


In [3]:

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a)
print("Elemento en fila 1, columna 3:", a[1, 3])  # En MATLAB sería a(2,4)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elemento en fila 1, columna 3: 8



## 4. Creación de arrays especiales
NumPy ofrece funciones para crear arreglos de forma rápida:
- `np.zeros()` → array de ceros  
- `np.arange()` → secuencia con paso constante  
- `np.linspace()` → secuencia con espaciado lineal


In [4]:

# Arreglo de ceros (float por defecto)
c = np.zeros(3)

# Arreglo de ceros de tipo entero
d = np.zeros(3, dtype=np.int64)

# Secuencia con paso constante
e = np.arange(2, 9, 2)

# Valores espaciados linealmente
f = np.linspace(0, 10, 10)

print(f)


[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]



## 5. Copias y referencias
Para copiar datos de un array a otro, debemos hacerlo explícitamente para evitar modificar el original por accidente.


In [5]:

x = np.array([[3, 4, 5], [2, 3, -1]])
print(f"{x} de tipo {type(x)}")
print(f"{x.shape} de tipo {type(x.shape)}")

y0 = np.array([3, 5, 6])

# Crear un array con la misma forma que otro
a = np.zeros_like(y0)

# Copiar valores
a[:] = y0[:]

print(a)

# Matriz de ceros
b = np.zeros([4, 5])
print(b)


[[ 3  4  5]
 [ 2  3 -1]] de tipo <class 'numpy.ndarray'>
(2, 3) de tipo <class 'tuple'>
[3 5 6]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]



## 6. Mini ejemplo de graficación con Matplotlib
Aunque veremos gráficos en detalle más adelante, podemos mostrar rápidamente cómo graficar datos de un array.


In [6]:

import matplotlib.pyplot as plt

#Graficar el array f
plt.plot(f, marker='o')
plt.title("Ejemplo rápido de gráfica")
plt.xlabel("Índice")
plt.ylabel("Valor")
plt.grid(True)
plt.show()
